version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

jobs:  
  build_deploy:
    executor: aws-cli/default
    steps:
      - checkout

      - restore_cache: # Download and cache dependencies
          keys:
            - v1-dependencies-{{ checksum "app/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd app && npm install

      - save_cache:
          paths:
            - app/node_modules
          key: v1-dependencies-{{ checksum "app/package.json" }}

      - run: sudo apt install zip
      - run: |
          cd app
          zip -r deploy.zip node_modules index.js
          echo $(ls)
      
      - aws-cli/install:
          version: '2'

      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY

      - run: 
          command: cd app && sudo aws --no-paginate lambda update-function-code --function-name  send_email_hornbill --zip-file fileb://deploy.zip
          environment:
            TERM: xterm


          
workflows:
  version: 2
  build:
    jobs:
      - build_deploy:
        filters:
            branches:
              only:
                - master
