version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

jobs:  
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/deployed
    steps:
    - run : | 
        sudo apt install zip

    - run: |
        echo Running test
        sudo echo > /app
          
workflows:
  version: 2
  build:
    jobs:
      - build_deploy:
        filters:
            branches:
              only:
                - master
