version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

jobs:  
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout

      - restore_cache: # Download and cache dependencies
          keys:
            - v1-dependencies-{{ checksum "website/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd app && npm install

      - save_cache:
          paths:
            - website/node_modules
          key: v1-dependencies-{{ checksum "website/package.json" }}

      - run: sudo apt install zip
      - run: |
          cd app
          zip -r deploy.zip /app
          echo $(ls)

          
workflows:
  version: 2
  build:
    jobs:
      - build_deploy:
        filters:
            branches:
              only:
                - master
