version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

jobs:  
  build_deploy:
    executor: aws-cli/default
    working_directory: ~/devtest
    steps:
    - run : | 
        sudo apt install zip

    - run: |
        echo Running test
        sudo mkdir deployed
        ls
        zip deployed
          
workflows:
  version: 2
  build:
    jobs:
      - build_deploy:
        filters:
            branches:
              only:
                - master
